# (Github Dark Colorblind) Colors for Wezterm

[colors]
background = "#0d1117"
foreground = "#c9d1d9"

cursor_bg = "#c9d1d9"
cursor_border = "#c9d1d9"
cursor_fg = "#0d1117"

selection_bg = "#1e4273"
selection_fg = "#c9d1d9"

ansi = [
    "#484f58",
    "#ec8e2c",
    "#58a6ff",
    "#d29922",
    "#58a6ff",
    "#bc8cff",
    "#39c5cf",
    "#b1bac4",
]
brights = [
    "#6e7681",
    "#fdac54",
    "#79c0ff",
    "#e3b341",
    "#79c0ff",
    "#d2a8ff",
    "#56d4dd",
    "#ffffff",
]
